# Generated by Django 4.2 on 2024-12-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiAppMedicos', '0002_alter_medicomodels_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('obrasocial', models.CharField(max_length=8)),
                ('edad', models.IntegerField()),
                ('fechanacimiento', models.DateField()),
            ],
        ),
    ]
