# Generated by Django 4.2 on 2024-12-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiAppMedicos', '0003_pacientemodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientemodels',
            name='fechanacimiento',
        ),
    ]
