# Generated by Django 4.2 on 2024-12-15 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiAppMedicos', '0004_remove_pacientemodels_fechanacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiAppMedicos.medicomodels')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiAppMedicos.pacientemodels')),
            ],
        ),
    ]
